let all=[],lang="en";
const categories=["Nepal","Politics","Business","World","Sports","Entertainment","Technology"];
function esc(s){return String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
async function init(){all=await fetch("/api/articles").then(r=>r.json());let s=await fetch("/api/settings").then(r=>r.json());document.getElementById("contact").textContent=(s.email||"")+" • "+(s.phone||"");document.getElementById("social").textContent="Facebook • YouTube • TikTok";render()}
function card(n){let title=lang==="np"&&n.title_np?n.title_np:n.title_en;let summary=lang==="np"&&n.summary_np?n.summary_np:n.summary_en;return `<article class="card"><div class="cardimg">${n.image?`<img src="${esc(n.image)}" alt="">`:esc(n.category.toUpperCase())}</div><div class="cardbody"><small>${esc(n.category)}</small><h3>${esc(title)}</h3><p>${esc(summary)}</p><time>${new Date(n.published_at||n.created_at).toLocaleString()}</time></div></article>`}
function render(){let q=(document.getElementById("search").value||"").toLowerCase();let a=all.filter(n=>(n.title_en+n.title_np+n.summary_en+n.category).toLowerCase().includes(q));let f=a.find(x=>x.featured)||a[0];document.getElementById("featured").innerHTML=f?`<article class="featured"><div class="featuredimg">${f.image?`<img src="${esc(f.image)}">`:"FEATURED STORY"}</div><small>${esc(f.category)}</small><h2>${esc(lang==="np"&&f.title_np?f.title_np:f.title_en)}</h2><p>${esc(lang==="np"&&f.summary_np?f.summary_np:f.summary_en)}</p><a href="/article/${encodeURIComponent(f.slug)}">Read Full Story →</a></article>`:"<p>No published stories.</p>";document.getElementById("side").innerHTML=a.slice(0,6).map(n=>`<div class="side"><small>${esc(n.category)}</small><a href="/article/${encodeURIComponent(n.slug)}"><h3>${esc(lang==="np"&&n.title_np?n.title_np:n.title_en)}</h3></a></div>`).join("");document.getElementById("grid").innerHTML=a.slice(0,8).map(card).join("");categories.forEach(c=>{let el=document.getElementById(c+"Grid");if(el)el.innerHTML=a.filter(n=>n.category===c).slice(0,4).map(card).join("")})}
function toggleLanguage(){lang=lang==="en"?"np":"en";document.getElementById("language").textContent=lang==="en"?"नेपाली":"English";render()}
function subscribe(e){e.preventDefault();alert("Subscription form is ready. Connect an email provider for production.");e.target.reset()}
let headlines=["Welcome to The Civil Media Private Limited — Truth, People, Accountability.","Latest updates from Nepal and around the world.","Independent and responsible public-interest journalism."];let i=0;setInterval(()=>{i=(i+1)%headlines.length;document.getElementById("ticker").textContent=headlines[i]},4000);
init();